/**
 *  @file       EngineEnums.h
 *  @brief      Enum strings for the Engine module.
 *  @author     gdprop tool.
 *
 *  WARNING!
 *  This file has been autogenerated, all change made will be lost!
 */
#include "Engine.h"

#if GD_CFG_USE_PROPERTIES == GD_ENABLED

namespace Gamedesk
{

namespace EnumInfo
{
    namespace Renderer
    {
        class ENGINE_API PixelCompareFunc
        {
            DECLARE_ENUM_INFO();
        };
    }

    namespace Renderer
    {
        class ENGINE_API PixelBlendingFactor
        {
            DECLARE_ENUM_INFO();
        };
    }

    namespace Renderer
    {
        class ENGINE_API LightType
        {
            DECLARE_ENUM_INFO();
        };
    }

    namespace TextureStage
    {
        class ENGINE_API TextureMode
        {
            DECLARE_ENUM_INFO();
        };
    }

    namespace TextureStage
    {
        class ENGINE_API TextureCoordGenMode
        {
            DECLARE_ENUM_INFO();
        };
    }

    namespace IndexBuffer
    {
        class ENGINE_API Usage
        {
            DECLARE_ENUM_INFO();
        };
    }

    namespace IndexBuffer
    {
        class ENGINE_API LockType
        {
            DECLARE_ENUM_INFO();
        };
    }

    namespace VertexBuffer
    {
        class ENGINE_API Usage
        {
            DECLARE_ENUM_INFO();
        };
    }

    namespace VertexBuffer
    {
        class ENGINE_API LockType
        {
            DECLARE_ENUM_INFO();
        };
    }

    namespace Sound
    {
        class ENGINE_API eSoundMode
        {
            DECLARE_ENUM_INFO();
        };
    }

    namespace Sound
    {
        class ENGINE_API eSoundConstant
        {
            DECLARE_ENUM_INFO();
        };
    }

    namespace SoundSubsystem
    {
        class ENGINE_API eSpeakerMode
        {
            DECLARE_ENUM_INFO();
        };
    }

    namespace SoundSubsystem
    {
        class ENGINE_API eOutputType
        {
            DECLARE_ENUM_INFO();
        };
    }

    namespace SoundSubsystem
    {
        class ENGINE_API eMixerType
        {
            DECLARE_ENUM_INFO();
        };
    }

    namespace Keyboard
    {
        class ENGINE_API Key
        {
            DECLARE_ENUM_INFO();
        };
    }

    namespace Keyboard
    {
        class ENGINE_API KeyState
        {
            DECLARE_ENUM_INFO();
        };
    }

    namespace Mouse
    {
        class ENGINE_API Button
        {
            DECLARE_ENUM_INFO();
        };
    }

    namespace Mouse
    {
        class ENGINE_API Axis
        {
            DECLARE_ENUM_INFO();
        };
    }

    namespace Mouse
    {
        class ENGINE_API ButtonState
        {
            DECLARE_ENUM_INFO();
        };
    }

    namespace TestProperties
    {
        class ENGINE_API MyEnum
        {
            DECLARE_ENUM_INFO();
        };
    }

} // namespace EnumInfo
} // namespace Gamedesk

#endif
